repos:
  - repo: https://github.com/hhatto/autopep8
    rev: v2.0.2
    hooks:
      - id: autopep8
        args: ['.', '-d']
        exclude: '^src/assets/'

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.1.11'
    hooks:
      - id: ruff
        # Respect `exclude` and `extend-exclude` settings.
        args: ['--force-exclude']
